In [11]:
#intro to numpy

In [12]:
import numpy as np #alias , will use as numpy._ to use functions now use alias._

In [13]:
a=np.array([34,35,22,324,67],dtype=float)

#learn array will take homogenous data types unlike list , also using dtype can convert whole array in whicher homogenous data type you want
''' array in  symbolic form is [34,35,22,324,67] function to create array is np.array() outputs created array, inputs symbolic array form '''

' array in  symbolic form is [34,35,22,324,67] function to create array is np.array() outputs created array, inputs symbolic array form '

In [14]:
print(a)

[ 34.  35.  22. 324.  67.]

In [15]:
#nesting array in a big array in symbolic makes 2d array so in symbolic [] now put arrays inside this '[]' , so [[],[],[]] , if put array in array of big array 3d array , so [[[],[]],[[],[]],[[],[]]]
c=[[[2,4,5],[34,567,80]],[[233,563,2,24],[454,54,45,4]],[[4545454,45,54,3],[433,45,4,454]]]
print(c)

[[[2, 4, 5], [34, 567, 80]], [[233, 563, 2, 24], [454, 54, 45, 4]], [[4545454, 45, 54, 3], [433, 45, 4, 454]]]

In [16]:
#creating arrays using range so using a'range' command unlike normal range contains 1 less
d=np.arange(1,10)
print(d)
#after we know total number of elements inside normal array below 1x9 , can reshape as 3x3 also as long as total number of elements is same, we use reshape as array.reshape(no. of rows, no. of columns )
e=np.arange(1,10).reshape(3,3)
print(e)
#from output see this is 2d array can see using array.shape also empty function ouputs tuple, as _,_ filled so 2 spaces filled so 2d array , also tells the order
m= e.shape
print(m)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

In [17]:
f=np.zeros((4,))
#this np.zeros() takes   parameters as the order in symbolic form , so symbolic form is (3,3) , (4,) (2,3,4)
print(f)
#similalry np.ones()
g=np.ones((4,))
print(g)
#

[0. 0. 0. 0.]
[1. 1. 1. 1.]

In [18]:
#creating dataframe :-a)manual way of creating pandas dataframe(it  can contains heterogenous data) 1.using nesting of a tuple(acts as a row ), in a list ,(prep for later creating   dataframe) 2.then in other column creating command create a variable storing the final created table (data frame) then using pd.DataFrame() function pass the old preped rows-containg variable then ,columns=[list of coumns name ]), then assigns columns respectively

In [19]:
import pandas as pd
m=[('jaipur',40,'ishaan'),('bikaner',20,'rudraksh'),('kailash',50,'mohit raina')]
mt=pd.DataFrame(m,columns=['city','temp','name'])
print(mt)

      city  temp         name
0   jaipur    40       ishaan
1  bikaner    20     rudraksh
2  kailash    50  mohit raina

In [20]:
#b) using csv files importing using a final dataframe variable then pd.read_csv("file name.csv") after uploading the csv file (not under subfolders)
g=pd.read_csv("Data.csv")
print(g)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

## Pandas DataFrame Column Selection Notes
see dataframe vs series in pandas
When selecting columns from a pandas DataFrame (`df`):

*   **Selecting a single column as a Series:** Use single square brackets with the column name as a string: `df['ColumnName']`.
    *   Example: `g['Age']`

*   **Selecting a single column as a DataFrame:** Use double square brackets with the column name inside a list: `df[['ColumnName']]`.
    *   Example: `g[['Age']]`

*   **Selecting multiple columns as a DataFrame:** Use double square brackets with a list of column names: `df[['Column1', 'Column2', 'Column3']]`.
    *   Example: `g[['Country', 'Age', 'Salary']]`

The key distinction is that `df[]` with a string returns a pandas `Series`, while `df[[]]` with a list (even if it contains only one element) returns a pandas `DataFrame`.

In [28]:
print(g['Age'])
print(g[['Country','Age']])
print(g[['Country','Age','Salary']])

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64
   Country   Age
0   France  44.0
1    Spain  27.0
2  Germany  30.0
3    Spain  38.0
4  Germany  40.0
5   France  35.0
6    Spain   NaN
7   France  48.0
8  Germany  50.0
9   France  37.0
   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [35]:
#unlike above we use .loc[], .iloc[] for selecting rows only using indexed
print(g.loc[0])
# so see just above france
#like [[]] in above for columns for multiple rows here
print(g.loc[[0,1,2]])
print(g.iloc[0])
print(g.iloc[[0,1,2]])
#both .loc[] , iloc[] are similar ways

Country       France
Age             44.0
Salary       72000.0
Purchased         No
Name: 0, dtype: object
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
Country       France
Age             44.0
Salary       72000.0
Purchased         No
Name: 0, dtype: object
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

## Evaluation Notes for `g[g['Age']>30]`

This expression performs **boolean indexing** to filter the DataFrame `g` based on a condition applied to the 'Age' column. Here's a step-by-step breakdown:

1.  **`g['Age'] > 30` (Condition Evaluation):**
    *   First, the expression `g['Age'] > 30` is evaluated. This creates a pandas Series of boolean values (True/False).
    *   For each row in the 'Age' column, it checks if the age is greater than 30.
    *   **Example Output of `g['Age'] > 30`:**
        ```
        0     True  (44.0 > 30)
        1    False  (27.0 > 30)
        2    False  (30.0 > 30 is False)
        3     True  (38.0 > 30)
        4     True  (40.0 > 30)
        5     True  (35.0 > 30)
        6    False  (NaN > 30 is False, as NaN comparisons are typically false)
        7     True  (48.0 > 30)
        8     True  (50.0 > 30)
        9     True  (37.0 > 30)
        Name: Age, dtype: bool
        ```

2.  **`g[...]` (Boolean Indexing):**
    *   The resulting boolean Series is then used to index the original DataFrame `g`.
    *   Pandas selects only those rows from `g` where the corresponding value in the boolean Series is `True`.
    *   Rows with `False` (or `NaN` in the condition result) are excluded from the final output.
    as g[0,___]

**Result:** The expression `g[g['Age']>30]` returns a new DataFrame containing only the rows where the 'Age' is greater than 30.

In [36]:
#filtering putting conditional (outputting true values) on a dataframevaribale, then putting the result into the another dataframevariable to present the filtered list                                like g[g['Age']>30] , so only prints th

print(g[g['Age']>30])

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [39]:
#inseting a new coulmn at the end by default to inset at a specifc use .insert
#by default method  dataframe['new column label']=[content]
g['condition']=['g','i','s','h','a','a','n','s','a','h']
print(g)
#inserting at specific dataframe.insert(index,column label , [all values]) behind  column indexes readjust (check)
g.insert(2,'life',['g','i','s','h','a','a','n','s','a','h'])
print(g)

   Country   Age   Salary Purchased condition
0   France  44.0  72000.0        No         g
1    Spain  27.0  48000.0       Yes         i
2  Germany  30.0  54000.0        No         s
3    Spain  38.0  61000.0        No         h
4  Germany  40.0      NaN       Yes         a
5   France  35.0  58000.0       Yes         a
6    Spain   NaN  52000.0        No         n
7   France  48.0  79000.0       Yes         s
8  Germany  50.0  83000.0        No         a
9   France  37.0  67000.0       Yes         h
   Country   Age life   Salary Purchased condition
0   France  44.0    g  72000.0        No         g
1    Spain  27.0    i  48000.0       Yes         i
2  Germany  30.0    s  54000.0        No         s
3    Spain  38.0    h  61000.0        No         h
4  Germany  40.0    a      NaN       Yes         a
5   France  35.0    a  58000.0       Yes         a
6    Spain   NaN    n  52000.0        No         n
7   France  48.0    s  79000.0       Yes         s
8  Germany  50.0    a  83000.0        No         a
9   France  37.0    h  67000.0       Yes         h

In [44]:
#deleting columns
g.drop(columns=['life'])

   Country   Age   Salary Purchased condition
0   France  44.0  72000.0        No         g
1    Spain  27.0  48000.0       Yes         i
2  Germany  30.0  54000.0        No         s
3    Spain  38.0  61000.0        No         h
4  Germany  40.0      NaN       Yes         a
5   France  35.0  58000.0       Yes         a
6    Spain   NaN  52000.0        No         n
7   France  48.0  79000.0       Yes         s
8  Germany  50.0  83000.0        No         a
9   France  37.0  67000.0       Yes         h

In [45]:
#deleting multiple columns
g.drop(columns=['Salary','condition'])

   Country   Age life Purchased
0   France  44.0    g        No
1    Spain  27.0    i       Yes
2  Germany  30.0    s        No
3    Spain  38.0    h        No
4  Germany  40.0    a       Yes
5   France  35.0    a       Yes
6    Spain   NaN    n        No
7   France  48.0    s       Yes
8  Germany  50.0    a        No
9   France  37.0    h       Yes

In [46]:
#deleting row using index
g.drop(2)

   Country   Age life   Salary Purchased condition
0   France  44.0    g  72000.0        No         g
1    Spain  27.0    i  48000.0       Yes         i
3    Spain  38.0    h  61000.0        No         h
4  Germany  40.0    a      NaN       Yes         a
5   France  35.0    a  58000.0       Yes         a
6    Spain   NaN    n  52000.0        No         n
7   France  48.0    s  79000.0       Yes         s
8  Germany  50.0    a  83000.0        No         a
9   France  37.0    h  67000.0       Yes         h

In [48]:
#inserting a new row                        at specific index
g.loc[2]=['usa',34,'i',3445,'no','ishaan']
print(g)

   Country   Age life   Salary Purchased condition
0   France  44.0    g  72000.0        No         g
1    Spain  27.0    i  48000.0       Yes         i
2      usa  34.0    i   3445.0        no    ishaan
3    Spain  38.0    h  61000.0        No         h
4  Germany  40.0    a      NaN       Yes         a
5   France  35.0    a  58000.0       Yes         a
6    Spain   NaN    n  52000.0        No         n
7   France  48.0    s  79000.0       Yes         s
8  Germany  50.0    a  83000.0        No         a
9   France  37.0    h  67000.0       Yes         h

In [50]:
#updating field , first using intersection find row index , column name
g.loc[3,'Age']=30